## Analisis data twillio

In [1]:
import pandas as pd #lo primero es llamar a pandas

In [59]:
call_df = pd.read_csv("../../Datas_frames/call-log-26-2-2020.csv", delimiter =",",decimal=".") 
call_df = call_df.drop(call_df[call_df['Duration']<1].index) #Eliminamos las llamadas no tomadas
call_df['Price_pesos'] = call_df['Price']*53 #Creamos la col del precio en RD$
call_df.head()

,Sid,AccountSid,StartTime,EndTime,Duration,From,To,Direction,Status,ApiVersion,Price,PriceUnit,Price_pesos
0,CA18746f8d086051c1e74dd7372a1f3644,ACc6a703df4f94818ba563036d4a85a7f4,20:05:10 UTC 2020-02-26,20:05:55 UTC 2020-02-26,45,18299566546,18295716673,Outgoing API,Completed,2010-04-01,NaN,USD,NaN
1,CA7b73277c4533f3e911970e7b03db4dc7,ACc6a703df4f94818ba563036d4a85a7f4,20:05:30 UTC 2020-02-26,20:06:15 UTC 2020-02-26,45,18299566546,18295716673,Outgoing API,Completed,2010-04-01,NaN,USD,NaN
2,CA0805da72e89facc6cf4aaa33694cc023,ACc6a703df4f94818ba563036d4a85a7f4,18:28:52 UTC 2020-02-26,18:28:56 UTC 2020-02-26,4,18499191828,18299566546,Incoming,Completed,2010-04-01,-0.01,USD,-0.53
3,CA302f37dea85d26143e28b6801488d0e0,ACc6a703df4f94818ba563036d4a85a7f4,18:27:37 UTC 2020-02-26,18:27:41 UTC 2020-02-26,4,18499191828,18299566546,Incoming,Completed,2010-04-01,-0.01,USD,-0.53
4,CAb9996942ee4019c16832e1f34b5f29e1,ACc6a703df4f94818ba563036d4a85a7f4,18:10:58 UTC 2020-02-26,18:11:03 UTC 2020-02-26,5,18292049135,18299566546,Incoming,Completed,2010-04-01,-0.01,USD,-0.53

In [60]:
call_df.shape #Vemos cuantas filas y columnas tiene

(1918, 13)

In [44]:
call_df.describe() #Vemos la info mas importante de la data

#En fin podemos ver que el promedio duracion de las llamadas es de 33.57 segundos
#Con una desviacion tipica de 18 segundos

#Asi mismo vemos que en promedio cada llamada cuesta 5.5 pesos
#Con una desviacion tipica de 2.4 pesos
#Por lo que un cobro de 8 pesos deberia ser mas que suficiente, teniendo en cuenta esta muestra de 1918 llamadas
#Del 2015 al 2020

          Duration          From            To        Price  Price_pesos
count  1918.000000  1.918000e+03  1.918000e+03  1915.000000  1915.000000
mean     33.576121  1.802375e+10  1.817377e+10    -0.103986    -5.511280
std      18.272675  1.840216e+09  3.455367e+08     0.045625     2.418107
min       1.000000  2.666967e+08  1.203361e+10    -0.281000   -14.893000
25%      15.000000  1.829957e+10  1.809568e+10    -0.120000    -6.360000
50%      43.000000  1.829957e+10  1.809907e+10    -0.120000    -6.360000
75%      50.000000  1.829957e+10  1.829826e+10    -0.110000    -5.830000
max      79.000000  1.978894e+10  1.978845e+10    -0.010000    -0.530000